### ISSUE TITLE
[General] Isn't this just a pointer?

### ISSUE THREAD

**Issue by OzairP** [maierfelix/object-reflector#1]
I don't understand the point of this package. Seems like a glorified pointer? The values point to the same memory address in both objects. Whats the use of this?

**Comment by maierfelix** [comment]
In many cases you have to wrap data into an object to make it referenceable. This affects the code style in a bad way and makes data structures more complex. This library just allows you to directly share properties and primitive properties without making the code less readable or do any wrapping. Also see the use case [here](https://github.com/maierfelix/object-reflector#faq)
